### ISSUE TITLE
Flannel client should use certificate for etcd connection

### ISSUE THREAD

**Issue by r7vme** [giantswarm/kvm-operator#107]
Our host cluster etcd has [enabled client auth](https://github.com/giantswarm/hive/commit/27828171b64c5f9b5e434c6b802ab8197ffdbae4https://github.com/giantswarm/hive/commit/27828171b64c5f9b5e434c6b802ab8197ffdbae4)

We should use some certificate for flannel client.

We should mount `etcd-certs` volume inside `flannel-client` container and [few flannel options](https://github.com/coreos/flannel/blob/master/Documentation/configuration.md#key-command-line-options)

```
--etcd-keyfile="": SSL key file used to secure etcd communication.
--etcd-certfile="": SSL certification file used to secure etcd communication.
--etcd-cafile="": SSL Certificate Authority file used to secure etcd communication.
```

**Comment by xh3b4sd** [comment]
FYI flannel operator already uses certificates to authenticate against etcd.

**Comment by xh3b4sd** [comment]
I see that the flannel clients that are created by the flannel operator still do not use the etcd certificates. See https://github.com/giantswarm/flannel-operator/blob/d2677bc5dcf9353d0a45336df9a7b4ecae634253/service/flannel/daemonset.go#L62. I think we could just use the certificates here that the flannel operator uses already.

**Comment by calvix** [comment]
good catch, that's the one that should be updated i guess
