### ISSUE TITLE
Reschedule of master pod will cause data etcd loss

### ISSUE THREAD

**Issue by r7vme** [giantswarm/kvm-operator#122]
We are storing data in local directory on [host](https://github.com/giantswarm/kvm-operator/blob/master/service/resource/master/deployment.go#L76), this means that data will be lost if for some reason kubernetes decides to move pod to another node (e.g. node failure)

**Comment by calvix** [comment]
I would say we can close this because we either store or NFS or will use PV for that

We decided that we won't ever run installation without storage again.

So this should never happen again
