### ISSUE TITLE
Add command-line specifiable selector

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/kvm-operator#24]
We're probably gonna want to run test builds of the cluster-controller on G8S

If we can specify a selector for the cluster-controller by the command line, which the listwatch respect, we should be able to run multiple cluster-controllers, and have them work on specifically labelled cluster resources

e.g: production cluster-controller runs with --selector=cluster=production
and a test cluster-controller runs with --selector=cluster=joe-test-1

The production cluster only works on cluster resources labelled with cluster=production, and this exemplar test cluster-controller only works on cluster resources labelled with cluster=joe-test-1

**Comment by calvix** [comment]
afaik this is implemented by label selector ( used ie for kvm CI)
