### ISSUE TITLE
Specify CPU/memory limits on k8s-kvm container

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/kvm-operator#259]
Follow up issue, as requested in https://github.com/giantswarm/giantswarm/issues/1173#issuecomment-346309295

**Comment by puja108** [comment]
+1 we need to set `limits` equal to `requests` as only that gets them into the `guaranteed` class in the k8s scheduler. This class is the last one that gets killed/rescheduled on pressure

**Comment by calvix** [comment]
in that case we need increase request and limits to have the overhead of qemu in place

**Comment by kopiczko** [comment]
Can you roughly tell the overhead?

**Comment by calvix** [comment]
Its hard to find any documents here, from my testing it's around +1GB of memory.



Do you have any insight from OpenStack guys? @r7vme @corest?

**Comment by r7vme** [comment]
In OpeStack we just reserved 4Gb of memory per hypervisor for OS, this includes OpenStack procesess, libvirt and qemu.

Just want to understand why we want to hard-limit resources for VM?

We already have this limited by qemu. I would avoid setting additional hard limit, as i don't see use case where it should help, but it can cause some troubles if OOM killer will decide to delete pod.

**Comment by r7vme** [comment]
I see Puja's comment about `guaranteed` group. Ok then let's start with +500MB . We can test this 

```
sudo mount -t tmpfs none /mnt/
dd if=/dev/zero of=/mnt/1 bs=$((1024*1024)) count=<in megabytes>
```

Use number bigger than free memory.

**Comment by calvix** [comment]
IMHO we should use +1GB for memory as 500MB seems too low from my testing and it will be hard to test it in our testing ENV

**Comment by r7vme** [comment]
We can start with +1Gb.

**Comment by kopiczko** [comment]
Thank you! Now it's clear. Adding boyscouting label.
